service: contacts.api
providers:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1

functions:
  - '${file(src/handlers/contacts/contacts.serverless.yml)}'

plugins:
  - serverless-offline